### ISSUE TITLE
Case mismatch

### ISSUE THREAD

**Issue by o0beaner** [Digitalroot/MediaWiki_PHPBB_Auth#1]
The Auth_phpBB.php file has the B's in phpBB in lower-case, whereas the line:

require_once './extensions/Auth_phpBB.php';

has them capitalized. This causes MediaWiki to choke.

**Comment by JWPlatt** [comment]
The fix unfortunately accommodated the original cause which was changing Auth_phpBB.php to Auth_phpbb.php.  It should be returned to Auth_phpBB.php and the line referenced in this closed issue also restored to Auth_phpBB.php.
