### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by zedwick** [Digitalroot/MediaWiki_PHPBB_Auth#15]
Am having trouble logging into MediaWiki 1.26 using v3.1.1 of this extension.

When I try to log in, I see:

`Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/ctr/www/w/extensions/Auth_phpbb.php on line 435

Notice: Trying to get property of non-object in /home/ctr/www/w/extensions/Auth_phpbb.php on line 438

Notice: Trying to get property of non-object in /home/ctr/www/w/extensions/Auth_phpbb.php on line 445

Fatal error: Call to a member function prepare() on resource in /home/ctr/www/w/extensions/Auth_phpbb.php on line 448`

I have my phpbb tables in the same DB as MediaWiki, and therefore have the following in my LocalSettings.php:

`$wgAuth_Config['UseExtDatabase'] = false;       // This tells the plugin that the phpBB tables
                                                // are in a different database then the wiki.
                                                // The default settings is false.

//$wgAuth_Config['MySQL_Host']        = 'localhost';      // phpBB MySQL Host Name.
//$wgAuth_Config['MySQL_Username']    = 'username';       // phpBB MySQL Username.
//$wgAuth_Config['MySQL_Password']    = 'password';       // phpBB MySQL Password.
//$wgAuth_Config['MySQL_Database']    = 'database';       // phpBB MySQL Database Name.

$wgAuth_Config['UserTB']         = 'phpbb_users';       // Name of your PHPBB user table. (i.e. phpbb_users)
$wgAuth_Config['GroupsTB']       = 'phpbb_groups';      // Name of your PHPBB groups table. (i.e. phpbb_groups)
$wgAuth_Config['User_GroupTB']   = 'phpbb_user_group';  // Name of your PHPBB user_group table. (i.e. phpbb_user_group)
$wgAuth_Config['PathToPHPBB']    = '../forum/';         // Path from this file to your phpBB install.`

**Comment by C4K3** [comment]
Funny I didn't notice this in the code in #12, but for some reason that part of the code was never updated to use MySQLi, I must have missed it.

For now set UseExtDatabase to true, and then just enter the same database information. That should work.

**Comment by XnIcRaM** [comment]
I have MediaWiki and phpBB 3.1.9 in the same database but it won't work until I set `$wgAuth_Config['UseExtDatabase']` to `true` and also set all MySQL related settings (remember to uncomment this lines and set proper username, password and database name.

If it's still doesn't work write your php, MySQL ans MediaWiki version.

**Comment by zedwick** [comment]
Can confirm that UseExtDatabase = true and supplying all the DB info in there does work, thanks.

I then also saw similar messages to: http://stackoverflow.com/questions/12048453/non-static-method-utf-normalizernfc-should-not-be-called-statically when attempting to logging in, which I fixed using this answer: http://stackoverflow.com/a/26066799

I'm not sure if there's anything that can be done on your end for this, so should I create an issue for it or forget it?

**Comment by C4K3** [comment]
If I'm reading it correctly that's a bug in phpbb, and not in this extension.

So nothing to be done here, though you might report it to the phpbb team.
