### ISSUE TITLE
Authenticated users

### ISSUE THREAD

**Issue by RichterSR** [Digitalroot/MediaWiki_PHPBB_Auth#17]
Hi,

I have tested this mod today and found out, that if I restricted reading Access to authenticated users while using this mod, all of them can also edit the WIKI Pages.

So, is it possible to restric reading to authenticated users:

`$wgGroupPermissions['user']['read'] = true;`

and only allow users in

` $wgAuth_Config['WikiGroupName'] = ('Wiki')`

to edit sites?

Kind Regards. :-)

**Comment by C4K3** [comment]
If I understand your question correctly, you want a wiki that is only readable by logged in users, you want regular logged in users to be able to read but not write, and you want users in the phpbb group Wiki to be able to read and write?

I don't think that's going to be possible with this extension, this extension only handles user login, not permissions once logged in. $wgAuth_Config['WikiGroupName'] restricts who is allowed to log in, but nothing else.

You would have to manually assign sysop or something to all the users you'd want to have write permissions, and then restrict writing to sysops.

**Comment by Digitalroot** [comment]
C4K4 is correct. Group management needs to be handled by the respective application.
