### ISSUE TITLE
phpBB 3.2 and Class 'Patchwork\\Utf8\\Bootup' not found

### ISSUE THREAD

**Issue by C4K3** [Digitalroot/MediaWiki_PHPBB_Auth#19]
So with phpBB 3.2 you get the error `Class 'Patchwork\\Utf8\\Bootup' not found`. This is manifest by a mediawiki error that says `Exception encountered, of type "Exception"` if ShowExceptionDetails is false.

I'll preface this by saying I'm not an expert on composer or php packaging. What I think is happening is that since Auth_phpbb.php includes `phpBB/includes/utf/utf_tools.php` (line 689), and that file uses something from `Patchwork\\Utf8\\Bootup`. `patchwork/utf8` is included in phpBB's composer.json, but not in mediawiki's composer.json. So I assume Auth_phpbb runs in mediawiki's context, and so only autoloads composer packages listed in mediawiki's composer.json, and so the utf_tools.php file can't find the Patchwork package, leading to the error.

I solved it by adding the patchwork/utf8 package found in phpBB/composer.json to mediawiki's composer.json and ran composer update, and then everything started working. This should however not be necessary from a user perspective.

Edit 2017-01-08: Clarified my hypothesis.

**Comment by Digitalroot** [comment]
I have not done any work to get the plugin to work via composer. I am intrigued by the idea

**Comment by karimcambridge** [comment]
Having this same issue.

**Comment by AzhureRx** [comment]
I'm also experiencing this issue following the phpBB 3.2 update. 

@C4K3 : How easy is it do what you said you had to do? Consider me as someone who can follow step by step instructions, but doesn't have the php knowledge to figure these things out myself.

**Comment by C4K3** [comment]
@AzhureRx It's not too hard, the hardest part should be to get composer installed. Check if it's installed first (look for a composer.phar file, or just run `composer --version` on the server.) If it's not installed, google how to install it for your distro, or alternatively use https://getcomposer.org/download/

Then open your phpBB/composer.json file, and look for the line that begins with `"patchwork/utf8"`, copy that line into the mediawiki/composer.json file, under the same section (i.e. below the `"require": {` line.) Then inside the mediawiki directory, run `composer update` (or `php composer.phar update` depending on how you installed composer.)

**Comment by AzhureRx** [comment]
@C4K3 You are a god! This fixed everything for me. Thank you so much for your help. :)
