### ISSUE TITLE
Error, hopefully others have seen... Table 'alliance_forum.sessions' doesn't exist [1146]

### ISSUE THREAD

**Issue by grungyape** [Digitalroot/MediaWiki_PHPBB_Auth#21]
We have phpbb3 in /forum, we have mediawiki 1.26.4 in /wiki 
We have separate databases, alliance_forum, alliance_wiki

It appears that nothing in the 3 files allows me to set my table prefix, and clearly something is assuming I don't have one.  I really needs to be looking at: alliance_forum.phpbb_sessions

Anyone have a fix?

**Comment by C4K3** [comment]
This extension does not use the phpbb sessions table, it only uses the users table, groups table, and user_group table. Could you post the full error, and say when it's happening?

You can't specify the prefix, but you can specify (actually are required to) the name of the 3 tables this extension relies on, these are the $wgAuth_Config['UserTB'], $wgAuth_Config['GroupsTB'] and $wgAuth_config['User_GroupTB'] in your wiki's LocalSettings.php. It should never be necessary to edit any of this extensions files.

**Comment by grungyape** [comment]
Oh geez, I just pulled a complete moron move.  I have been trying to get either the MediaWiki_PHPBB_Auth extension, or the phpBB Single Sign-On extension to work, and I posted the current error to the wrong one.

On the flip side, MediaWiki_PHPBB_Auth produces no error, but also provides no log in... if I tail the apache2 error log file or mysql...nothing.

As mentioned, separate databases, so external db is enabled and filled in.

**Comment by C4K3** [comment]
Ah no problem, we all do that sometimes.

When you say provides no login, does it give a blank screen, does it give an error, or does it say wrong password?

**Comment by grungyape** [comment]
If I visit phpbb3, where I have an account, and log in: https://auth.fubar-alliance.com/forum

Then I go directly to the wiki, I get a standard front page: https://auth.fubar-alliance.com/wiki2/index.php/Main_Page

I see no message as if anything is happening, but also see no errors in logs that something is breaking.

**Comment by C4K3** [comment]
That's because this extension works differently from mediawiki SSO, unlike SSO, this extension doesn't use the session data, it replaces mediawiki's authentication with the phpbb, so people log in to the wiki with the same username/password as they do on phpbb. In other words, you register on the forum, but then you have to log in on the wiki (with the same username/password,) but the login sessions on the wiki and forum are completely separate (i.e. logging into one will not log into the other.)

**Comment by grungyape** [comment]
Wow, I'm an idiot... somehow I assumed it was similar.  OK, so this puts me on the path, I just tried logging in with the same user/pass I have on phpbb and got a 500 message:

[Sun Feb 05 16:45:32.964627 2017] [:error] [pid 345] [client 206.51.161.242:65482] PHP Fatal error:  Class 'Patchwork\\Utf8\\Bootup' not found in /var/www/forum/includes/utf/utf_tools.php on line 27, referer: https://auth.fubar-alliance.com/wiki2/index.php?title=Special:UserLogin&returnto=Main+Page

So, I'll start tracing this out.... thanks for setting me straight.

**Comment by C4K3** [comment]
No problem. The error you're getting there is #19, an incompatability with phpbb 3.2 that was fixed in release 3.3.0. So just update to the latest extension version to fix that.

**Comment by grungyape** [comment]
SO, after installing composer, adding the patchwork lines, updating I Now get... 

Login error 
You have not specified a valid username.

so, that's a better start.

**Comment by grungyape** [comment]
Random question, I have two accounts on phpbb. I discovered I can log in with one of them. 

My main account, well call it "adminuser" has admin access, and can log into the ACP.  
My user account, "normaluser" does not.

I can log into mediawiki with the normaluser account, but the adminuser account says invalid username.

Is there a reason, can we change this at all?  Last question for now, I cannot log in with my mediawili admin account suddenly (maybe I didn't notice before) is this blocked due to the phpbb authentication?

**Comment by C4K3** [comment]
phpbb ACP access should not make any difference, likely adminuser has a name that is invalid for mediawiki, see #2.

If you made your mediawiki admin account before you added this extension, you will not be able to log into it anymore, unless you make a phpbb account with the same name (and in fact you may want to do that, to prevent some random user from claiming that username.) This is because the extension completely takes over the mediawiki authentication.

**Comment by grungyape** [comment]
Ug, dead on, its the underscore.  This is a problem.  I'm not 100% sure if it's an EvE Online thing or not, but we have a lot of usernames with _ often first_last

I'll have to ask the people who do the whole account sync with EvE (to the site, slack, phpbb, etc. and see if anything can be done or if there is a way to allow them in mediawiki.  

Thanks, you've been a great help.

**Comment by C4K3** [comment]
No problem, I hope you get it working the way you want.

There's a patch floating around that converts underscores into spaces (which mediawiki accepts,) but it's not supported here, and we can't guarantee its quality or anything.
