### ISSUE TITLE
Auth_phpbb.php should be corrected and restored to the original Auth_phpBB.php casing.

### ISSUE THREAD

**Issue by JWPlatt** [Digitalroot/MediaWiki_PHPBB_Auth#24]
The original casing was Auth_phpBB.php, which is how phpBB styles it.

**Comment by Digitalroot** [comment]
Good point. I do not remember when this was changed.

**Comment by C4K3** [comment]
My 2 cents: It is a very minor issue, and changing it would be a breaking change for all extension users.

**Comment by JWPlatt** [comment]
It was a breaking bug in the first place that shouldn't have happened.  It forced me to make an edit.  Erros should be corrected - not adopted.

**Comment by Digitalroot** [comment]
I'll correct this in a future release.

**Comment by JWPlatt** [comment]
When is the next release?

**Comment by C4K3** [comment]
It may be best to change this at the same time we implement the new extension registration
https://www.mediawiki.org/wiki/Manual:Extension_registration
as that will also require changes from users.

**Comment by Digitalroot** [comment]
Fixed in v3.4.1
