### ISSUE TITLE
Will this work with the latest MediaWiki updates?

### ISSUE THREAD

**Issue by karimcambridge** [Digitalroot/MediaWiki_PHPBB_Auth#25]
https://www.mediawiki.org/wiki/MediaWiki_1.26 also in 1.27 there are new AuthManager updates

http://image.prntscr.com/image/c827a25f582144daa796031299d59b6d.png

Will this work in 1.28?

**Comment by C4K3** [comment]
Yes it works in 1.28, the AuthPlugin interface is just deprecated but still works. See #14 for errors related to this.

**Comment by karimcambridge** [comment]
Thanks.
