### ISSUE TITLE
Discrepancy between file included and according error message

### ISSUE THREAD

**Issue by jhf2442** [Digitalroot/MediaWiki_PHPBB_Auth#26]
MediaWiki_PHPBB_Auth line 683 : 
if (!is_file($this->_PathToPHPBB . 'includes/utf/utf_tools.php'))
                {
                    throw new Exception('Unable to find phpbb\'s utf_tools.php file at (' . $this->_PathToPHPBB . '/includes/utf/utf_tools.php). Please check that phpBB is installed.');
                }

is_file concatenates without adding a slash, thus expecting a trailing slash in the PathToPHPBB variable, but the exception concatenates with a slash in the second string
So if the trailing slash is missing in the variable an exception will be thrown but the error message is very misleading

As line 696 finally includes the file (3rd concatenation of the path), wouldn't it be better to use a temp variable to hold the file name in order to remain consistent accross all uses : 
$utfTools=$this->_PathToPHPBB . '/includes/utf/utf_tools.php;
if (!is_file($utfTools)
                {
                    throw new Exception('Unable to find phpbb\'s utf_tools.php file at (' . $utfTools.'). Please check that phpBB is installed.');
                }
require_once $utfTools;

**Comment by C4K3** [comment]
I agree the inconsistency particularly in the error message should be considered a bug. I doubt a temp variable would even waste any performance, surely a variable is less performance than concatenating the path. But if adding a temp variable would is a problem, then I suggest we just change the code so that the path is concatenated consistently.

**Comment by jhf2442** [comment]
Consistent concatenation would be sufficient for me - so that the error message gives a helpful hint at the real issue.
Temp variable was just a suggestion to guarantee consistency, but up to you - I'll not argue on this topic
