### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by agreements** [Digitalroot/MediaWiki_PHPBB_Auth#28]
Thinking it's because of the line here:
$wgAuth_Config['PathToPHPBB']    = '../phpbb/';         

However since my forum is in a subdomain and the same with wiki, then what do i write here?
(using plesk)
My root folder just displays /
Wiki location: /wiki.domain.com
phpbb:  /forums.domain.com

**Comment by C4K3** [comment]
It doesn't matter the URL of the wiki/forum, what matters is that the wiki extension can read some specific phpbb files, so you should put the path to the phpbb directory in the server's file system. If they're on completely different servers, you'll need to download phpbb and put it into a directory on the mediawiki server, even though you aren't going to run phpbb there, but just so that mediawiki can get the phpbb files.

And just to be safe, try it without the /.

**Comment by agreements** [comment]
Unfortunelly the / didn't work out, still error 500. 
Complete path to forums:
/var/www/vhosts/myrootdomain.com/forums.mydomain.com/
/var/www/vhosts/myrootdomain.com/wiki.mydomain.com/

**Comment by C4K3** [comment]
Right, then you would set PathToPHPBB to be ../forums.mydomain.com. If that doesn't work, please post the full exception (turn on debugging in mediawiki.)

**Comment by agreements** [comment]
Fatal error: Call to a member function bind_param() on boolean in /extensions/Auth_phpbb.php on line 507

**Comment by C4K3** [comment]
That sounds like a MySQL error. Check that your have MySQLi enabled in your php.ini, and that the database settings are correct.

**Comment by agreements** [comment]
It is, and database settings is imported from config.php from phpbb root folder.

**Comment by agreements** [comment]
changed apache to nginx and that worked (no idea why)
But.. [4d622f167bef525bb179b9ab] 2017-04-30 12:38:56: Fatal exception of type "Error"

**Comment by agreements** [comment]
Ok i made some shit. Reinstalled server now works. 
However i can't login using forum creds.

**Comment by C4K3** [comment]
I'm not sure what the problem is then, try enabling full stacktraces (`$wgShowExceptionDetails = true;` in LocalSettings.php.)

And post your php, mediawiki, phpbb, and this extension's version.

**Comment by agreements** [comment]
Was bug on the webserver. Reinstalled the server and it worked. 
However if i use phpbb 3.1 can this still work then?

**Comment by C4K3** [comment]
Good you got it working.

I think it'll work with phpbb 3.1, but it's not supported, i.e. untested. If it doesn't work, you can grab one of the old releases that is tested with phpbb 3.1 (but then of course you won't be getting any updates.)
