### ISSUE TITLE
How to make it works on subdomain ?

### ISSUE THREAD

**Issue by mystya** [Digitalroot/MediaWiki_PHPBB_Auth#32]
Hi everyone,

I'm not sure how to configure this line :
- require_once './extensions/Auth_phpbb.php

My phpbb board is on mydomain.net and I installed a fresh mediawiki on wiki.mydomain.net. Both with their own db.
Phpbb is running version 3.2.2 and Mediawiki 1.30.0. The website is hosted on php 7.0.27 with mariadb for the databases.

I've got a warning because mediawiki can't find it's path to phpbb extensions folder.

How can I make it works ?

Here is my folder path :
- Phpbb : www/mydomain.net/htdocs/extensions/Auth_phpbb.php/
- Mediawiki : www/wiki.mydomain.net/htdocs/LocalSettings.php/

Thanks for your help ! :)

**Comment by C4K3** [comment]
The Auth_phpbb extension goes into the mediawiki extension directory. So you'd put it in your www/**wiki**.mydomain.net/htdocs/extensions/ directory, not the phpbb extensions directory.

So your tree should contain something like
```
├── LocalSettings.php
└── extensions
     ├── iAuthPlugin.php
     ├── PasswordHash.php
     └── Auth_phpbb.php
```

**Comment by mystya** [comment]
Hahaha ! It works like a charm by uploading those files in the right directory...
Sorry I feel so stupid to bother you for such a noob mistake. I should have thought about it ! ><

**Comment by C4K3** [comment]
No problem, glad you got it working :)
