### ISSUE TITLE
AuthPlugin is deprecated, MediaWiki 1.33 completely removes it: extension now dead

### ISSUE THREAD

**Issue by Wohlstand** [Digitalroot/MediaWiki_PHPBB_Auth#35]
MediaWiki have marked this feature to be deprecated: https://www.mediawiki.org/wiki/AuthPlugin
And it still exists for a long time. However, since 1.33 it got completely nuked and no more works.
Here is a manual how to upgrade API for that: https://www.mediawiki.org/wiki/Manual:SessionManager_and_AuthManager/Updating_tips#The_AuthPlugin_and_AuthPluginUser_classes

**Comment by Digitalroot** [comment]
Yikes!

**Comment by Wohlstand** [comment]
Once I'll find free time, I'll try to port this whole thing by myself... I needed for it a lot :thinking:

**Comment by heinrich-k** [comment]
I'd appreciate that...

**Comment by gizmocuz** [comment]
@Wohlstand , did you manage to help us out ?

**Comment by Wohlstand** [comment]
I have tried to do some on my end, no guarantee I'll make that quick, it's dependent on my free time. In a first post, I have explained that it needs to refactor the whole class from AuthPlugin into AuthManager to make it work again.

**Comment by Wohlstand** [comment]
P.S. First off I have merged my fork with minor fixes with updates of master branch: https://github.com/WohlSoft/MediaWiki_PHPBB_Auth/tree/wohlsoft%2Bmaster

**Comment by gizmocuz** [comment]
@Wohlstand , i would like to help, but I am a little bit occupied with my opensource project... and I would have to read up with creating plugins for mediawiki.
So I enabled the normal user creation two days ago... and forgot to enable captcha protection, resulting in 1000'ends of spam messages being send, spam wiki pages etc...
I do miss this plugin ;)

**Comment by Wohlstand** [comment]
>  So I enabled the normal user creation two days ago... and forgot to enable captcha protection, resulting in 1000'ends of spam messages being send, spam wiki pages etc...

Speaking about captcha: I made a trick in "question-answer" which gives protection and confuse of bots:
```
Please type "еvеrуоnе", don't copypaste, be aware alien characters
```
Why copypaste will not work? I have replaced several letters with the same shape as Latin, are taken from another alphabet (Cyrillic for example).

**Comment by C4K3** [comment]
I added a small $20 bounty for this on bountysource for anybody who wants to take this on (or add more to the bounty :-) )

https://www.bountysource.com/issues/77981236-authplugin-is-deprecated-mediawiki-1-33-completely-removes-it-extension-now-dead

**Comment by kdschlosser** [comment]
I am not any good at PHP. I know enough to get myself into trouble.
Give this a shot and see if it works.
https://github.com/kdschlosser/MediaWiki_PHPBB_Auth

make sure you check the code example in the readme. there is an additional require once line.

**Comment by Wohlstand** [comment]
I think, if it good at me, Ill try to compose a pull-request that:
- adds these new patches
- organizes plugin directory to make it look nice as other plugins looks, not like a trashbin

**Comment by kdschlosser** [comment]
I am getting thumbs up.. But does the thing work?? I have not had the time to test it yet and I won't be able to for at least another week or so.

**Comment by Wohlstand** [comment]
> I am getting thumbs up.. But does the thing work?? I have not had the time to test it yet and I won't be able to for at least another week or so.

Didn't test yet, but I going to test that as soon as possible, I'll report the result once I'll do that test.

**Comment by Wohlstand** [comment]
> I am getting thumbs up.. But does the thing work?? I have not had the time to test it yet and I won't be able to for at least another week or so.

Okay, the first error I got:
```
<br />
<b>Parse error</b>:  syntax error, unexpected 'return' (T_RETURN) in <b>www/wiki/extensions/Auth_phpBB/Auth_phpBB.php</b> on line <b>861</b><br />
```

And when I fixed that missing semicolon, I got next:
```
<br />
<b>Fatal error</b>:  Uncaught Error: Class 'AuthManager' not found in www/wiki/extensions/Auth_phpBB/Auth_phpBB.php:98
Stack trace:
#0 www/wiki/LocalSettings.php(255): require_once()
#1 www/wiki/includes/Setup.php(124): require_once('/bhome/part3/03...')
#2 www/wiki/includes/WebStart.php(81): require_once('/bhome/part3/03...')
#3 www/wiki/index.php(41): require('/bhome/part3/03...')
#4 {main}
  thrown in <b>www/wiki/extensions/Auth_phpBB/Auth_phpBB.php</b> on line <b>98</b><br />
```

I think, it's need to look for paths a bit diffetently...

**Comment by Wohlstand** [comment]
@kdschlosser , I did some fix of your code:
https://github.com/Wohlstand/MediaWiki_PHPBB_Auth/commit/4ab0d2a2f1b901fe343204928ec1fcb9acc1f3d0
Anyway, it's need to test the whole work around, it's probably some other bugs exist...

**Comment by Wohlstand** [comment]
Also, it tells that the "AuthChangeFormFields" hook is invalid, however, idk yet how to properly handle the extension yet. I tried to use `wfLoadExtension( 'Auth_phpBB' );` and attempt to open a login page, gives ne an error.

**Comment by kdschlosser** [comment]
again I am not proficient at anything PHP, and how MediaWiki is set up is way over my head. But I do believe that I have the right basic idea and it is in the right direction. I am going to see if get some help with this from possibly one of the developers over at MediaWiki or maybe someone that knows how the new authentication works.

I know there is a typo I commented on that line. I am also going to look at how the hooks were done in the original plugin and see if that same mechanism can be used to get the hooks working with this.

**Comment by Digitalroot** [comment]
See the new release https://github.com/Digitalroot/MediaWiki_PHPBB_Auth/releases/tag/v3.5.0

#36, Thanks to @joelhaasnoot

Update to PHP 7.3 & MediaWiki 1.31 LTS

**Comment by JWPlatt** [comment]
This is most appreciated, and great timing!  However, most of the diff is a large number of needless format changes, so it's difficult to see what actually changed.

**Comment by kdschlosser** [comment]
It looks like what has changed is how the passwords are handled with PHPBB 3.3 and that is the big thing the  new release fixes. It does not solve the problem with MediaWiki 1.33 which is what this issue thread is about.

**Comment by cpeel** [comment]
I, too, need the ability for the new MediaWiki LTS 1.35 to authenticate to phpBB 3.3. I have opened an MR (https://github.com/Digitalroot/MediaWiki_PHPBB_Auth/pull/42 -- an auspicious number!) that changes Auth_phpBB to use the [PluggableAuth](https://www.mediawiki.org/wiki/Extension:PluggableAuth) extension which supports MediaWiki 1.27+. It's almost a drop-in replacement for the prior version after the installation of PluggableAuth.

Assistance testing the code in the MR -- particularly for sites that use `UseWikiGroup` and `UseWikiProfile` -- would be appreciated.

**Comment by Wohlstand** [comment]
Btw, the question: I see that there was an update to support the phpBB 3.3 that has the changed hashing algorithm. Can it work with the phpBB 3.1 or the compatibility got broken? I do use the phpBBex fork that wasn't majorly updated since 2016, it's directly based on phpBB 3.1.9.
