### ISSUE TITLE
Compatibility with PHPbb 3.3?

### ISSUE THREAD

**Issue by joelhaasnoot** [Digitalroot/MediaWiki_PHPBB_Auth#36]
I realize this repo isn't really updated anymore and the plugin fails to work under the newest versions of MediaWiki, but it works under the current LTS so that's good enough for me. However, I also upgraded to PHPBB3.3.1 and am getting the following error

`PHP message: PHP Deprecated:  crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format.`

Has anyone gotten this working? (it may actually be a PHP 7.3 issue...)

**Comment by Digitalroot** [comment]
Sounds like a PHP 7.3 issue. Looks like the crypt() method was deprecated. 

I think these are related. 
https://www.php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt
https://stackoverflow.com/questions/41272257/mcrypt-is-deprecated-what-is-the-alternative

**Comment by joelhaasnoot** [comment]
So it turns out that in PHP 3.2.x and PHP 3.3.x the password hashing algorithms changed and you can't get away with just using the one hashing function. This (so far lightly) tested uses the PHPBB hashing methods to check the password: https://github.com/joelhaasnoot/MediaWiki_PHPBB_Auth/commit/46a3a8d0178e13e754fb781e0407e24a93b2a1dd . YMMV - but a starting point if you are running MediaWiki 1.31 (which is still LTS and has AuthPlugins!)

**Comment by Digitalroot** [comment]
Thank you.
