### ISSUE TITLE
Upgrade to MW 1.35 Tries to create the same wiki user as exists but can't?

### ISSUE THREAD

**Issue by stemapplications** [Digitalroot/MediaWiki_PHPBB_Auth#45]
I don't understand the behavior or what to do. After upgrading to MW1.35.2 from 1.27.4 and phpBB 3.2.2 to 3.3.4, when logging into wiki,  getting the message:

Auto-creation of a local account failed: Username entered already in use. Please choose a different name.

No idea what to do on this one.
Here's my localsettings.php for the extension:

// PluggableAuth
wfLoadExtension( 'PluggableAuth' );
// $wgPluggableAuth_EnableAutoLogin
// $wgPluggableAuth_EnableLocalLogin
// $wgPluggableAuth_EnableLocalProperties
// $wgPluggableAuth_ButtonLabelMessage
// $wgPluggableAuth_ButtonLabel

// phpBB User Database Plugin. (Requires MySQL Database)
wfLoadExtension( 'Auth_phpBB' );
$wgAuth_Config = array(); // Clean.
$wgAuth_Config['UseCanonicalCase'] = true;
$wgAuth_Config['WikiGroupName'] = 'Wiki';
$wgAuth_Config['UseWikiGroup'] = true;
$wgAuth_Config['UseExtDatabase'] = false;
$wgAuth_Config['MySQL_Host']        = 'localhost';
$wgAuth_Config['MySQL_Port']        = '3306';
$wgAuth_Config['MySQL_Username']    = 'secret';
$wgAuth_Config['MySQL_Password']    = 'secret';
$wgAuth_Config['MySQL_Database']    = 'secret';
$wgAuth_Config['UserTB']         = 'forum_users';
$wgAuth_Config['GroupsTB']       = 'forum_groups';
$wgAuth_Config['User_GroupTB']   = 'forum_user_group';
$wgAuth_Config['PathToPHPBB']    = '../forum/';
$wgAuth_Config['URLToPHPBB']     = 'http://192.168.191.6:8031/forum/';
$wgAuth_Config['UseWikiProfile']   = false;
$wgAuth_Config['ProfileDataTB']    = 'forum_profile_fields_data';
$wgAuth_Config['ProfileFieldName'] = 'pf_wikiusername';
// Local
$wgAuth_Config['LoginMessage']   = '<b>Please register on the forums to login.</b><br /><a href="' . $wgAuth_Config['URLToPHPBB'] .
                                   'ucp.php?mode=register">Click here to create an account.</a>'; // Localize this message.
$wgAuth_Config['NoWikiError']    = 'You must be a member of the required forum group.'; // Localize this message.

**Comment by Digitalroot** [comment]
I missed this. Is this still an active issue?

**Comment by stemapplications** [comment]
I got it going and I can't remember how now.

**Comment by Digitalroot** [comment]
Sounds good
