### ISSUE TITLE
Does not work with PHP 7.4

### ISSUE THREAD

**Issue by mrfrenzy** [Digitalroot/MediaWiki_PHPBB_Auth#58]
While trying to login with PHP 7.4 the plugin uses empty values for username and password

Log output:
`2022-06-06 08:37:25 wiki_: authenticate: looking up phpBB account for ''

2022-06-06 08:37:25 wiki_: lookupPhpBBUser: no phpBB username matched ''

2022-06-06 08:37:25 wiki_: authenticate: no user record found for username ''
`
PHP output:

`Warning: The use statement with non-compound name 'User' has no effect in /var/www/wiki/extensions/Auth_phpBB/includes/Auth_phpBB.php on line 44

Notice: Trying to access array offset on value of type null in /var/www/wiki/extensions/Auth_phpBB/includes/Auth_phpBB.php on line 296

Notice: Trying to access array offset on value of type null in /var/www/wiki/extensions/Auth_phpBB/includes/Auth_phpBB.php on line 297
`

**Comment by cpeel** [comment]
I will look into this, but we are using the plugin with PHP 7.4 so I know it works.

**Comment by cpeel** [comment]
Can you please confirm that the underlying problem here is actually https://github.com/Digitalroot-Technologies/MediaWiki_PHPBB_Auth/issues/59?

**Comment by mrfrenzy** [comment]
I must apologize. You are correct.

If I have Mediawiki 1.38 and php7.3 there are a few errors.
If I have Mediawiki 1.38 and php7.4 there are a lot more errors.
This lead me to assume incorrectly that the plugin was not compatible with php7.4 since most of the errors went away when downgrading.

With Mediawiki 1.37 and php7.4 everything works fine!

**Comment by cpeel** [comment]
Not a worry, thank you for clarifying!
