### ISSUE TITLE
Does not work with Mediawiki 1.38 or later with PluggableAuth 6.x

### ISSUE THREAD

**Issue by mrfrenzy** [Digitalroot/MediaWiki_PHPBB_Auth#59]
This is just for information so other users don't waste time upgrading.

Mediawiki 1.38 and later uses a completely new PluggableAuth 6.0 which is not compatible with PHPBB_Auth

That means we have to stick with Mediawiki 1.35 or 1.37 for now.

**Comment by cpeel** [comment]
I've opened a PR to support PluggableAuth 6.1. I've tested this on MediaWiki 1.35 and would appreciate some additional testing if you have the time.
