### ISSUE TITLE
wiki/extensions/Auth_phpbb.php on line 884

### ISSUE THREAD

**Issue by AzhureRx** [Digitalroot/MediaWiki_PHPBB_Auth#8]
I've been using this plugin for three years now, and I love it. I was really interested in the update when I saw that the plugin was updated a few weeks ago. 

Since I updated, newly added users to the wiki group on my forums are receiving this error: 

Fatal error: Call to undefined method mysqli::esacpe_string() in /home/arangoth/public_html/wiki/extensions/Auth_phpbb.php on line 884

When they try to log in. It appears that the forums are not creating the new users for the MediaWiki installation. The new users do not appear in the wiki's user list, and cannot log in. The old version of this plugin was continuing to work in my current environment, and this problem only came about when I updated the plugin. At this point, I may downgrade to resolve the issue. 

PHP: 5.3.29
MySQL: 5.5.38-35.2
MediaWiki: 1.26.2
phpBB: 3.1.18

My wiki and phpBB installs are not sharing a database and the configuration in LocalSettings.php reflects that. This is an English installation, and as I said before, this was working before I updated.

**Comment by Digitalroot** [comment]
Hi AzhureRx, I suggest rolling back. You should be able to grab older releases from https://github.com/Digitalroot/MediaWiki_PHPBB_Auth/releases . 

I will look into the issue.

**Comment by AzhureRx** [comment]
Thank you for the prompt reply! 

I have since rolled back to the previous version, which has restored functionality.

**Comment by haivala** [comment]
there's a typo in the function name 'esacpe' -> 'escape'

**Comment by RotimiBolorunduro** [comment]
@haivala which of the files?

**Comment by RotimiBolorunduro** [comment]
mine is working but  once i hit the login button it lands on a blank page...

**Comment by Digitalroot** [comment]
Try the new 3.1.1 release.

https://github.com/Digitalroot/MediaWiki_PHPBB_Auth/releases/tag/v3.1.1

Let me know if it resolves the issue.

**Comment by AzhureRx** [comment]
Awesome! That seems to have fixed things. It's creating new accounts with the new version.

Thank you for your help. :)

**Comment by Digitalroot** [comment]
Thanks to @haivala and @Kar2k too.
