### ISSUE TITLE
User Blank Page

### ISSUE THREAD

**Issue by RotimiBolorunduro** [Digitalroot/MediaWiki_PHPBB_Auth#9]
Hi Digitalroot,
Work well done, i love the development but i have little issues of blank pages after username and password authentication is passed it always land on a blank page... Please help me with how to fix it. Thank you.

**Comment by Digitalroot** [comment]
I am not 100% sure what is causing the problem you are experiencing. My guess is a php error. On my web host PHP error reporting is turned off, and the errors are printed into a **error_file** instead of to the browser. Maybe your host works the same way. Look around for how PHP errors are reported.

**Comment by Digitalroot** [comment]
Try the new 3.1.1 release.

https://github.com/Digitalroot/MediaWiki_PHPBB_Auth/releases/tag/v3.1.1

Let me know if it resolves the issue.

**Comment by RotimiBolorunduro** [comment]
Great, but i kind of get where the error is coming from..
2 PHP Notice and 1 PHP Fatal error on line 447.

Accoring to my error log it's;

> [12-Apr-2016 15:53:06 Etc/GMT] PHP Notice:  Trying to get property of non-object in /home/website/public_html/forum/wiki/extensions/Auth_phpbb.php on line 437

[12-Apr-2016 15:53:06 Etc/GMT] PHP Notice:  Trying to get property of non-object in /home/website/public_html/forum/wiki/extensions/Auth_phpbb.php on line 444

[12-Apr-2016 15:53:06 Etc/GMT] PHP Fatal error:  Call to a member function prepare() on a non-object in /home/website/public_html/forum/wiki/extensions/Auth_phpbb.php on line 447

**Comment by Digitalroot** [comment]
It looks like the mysqli object is failing to be created.
Would you provide more info on your setup?

PHP: ?
MySQL: ?
MediaWiki: ?
phpBB: ?

**Comment by RotimiBolorunduro** [comment]
do yo mean their version?

**Comment by Kar2k** [comment]
Yes he means the version of the person who is having the issue.

Could you also recheck your mysql config data for mediawiki. Make sure mediawiki is connecting to the db.

**Comment by RotimiBolorunduro** [comment]
@Kar2k everything about the mediawiki and db are connecting is OK!

**Comment by RotimiBolorunduro** [comment]
Oh yes i think is a MySQL connection problem.
When i set this to be true;

>         $wgAuth_Config['UseExtDatabase'] = false;       // This tells the plugin that the phpBB tables
                                                        // are in a different database then the wiki.
                                                        // The default settings is false.

I get an error message saying. 

> Exception encountered, of type "Exception"

**Comment by Kar2k** [comment]
"PHP Warning: mysqli::mysqli(): (28000/1045): Access denied for user 'website'@'localhost' (using password: NO)"

your website user probably has a password and your not entering a password. Maybe thats the issue?

**Comment by RotimiBolorunduro** [comment]
Please Where can I enter the code in the script?

**Comment by Digitalroot** [comment]
The Read Me file has all that info in it. Please look there.

**Comment by RotimiBolorunduro** [comment]
Yea, i read that. but it is only the code i apply at the the LocalSetting.php that i modified.
does it mean i have to modify the Auth_phpbb.php too? If yes, where?

**Comment by RotimiBolorunduro** [comment]
PHP: v5.4
MySQL: v?
MediaWiki: 1.26.2
phpBB: v3.1.8

**Comment by Digitalroot** [comment]
Would you post into this issue your LocalSettings.php file. I suggest masking username/password and host info before posting.

**Comment by RotimiBolorunduro** [comment]
`
        /*-----------------[ Everything below this line. ]-----------------*/
        
        // PHPBB User Database Plugin. (Requires MySQL Database)
        require_once './extensions/Auth_phpbb.php';
        
        $wgAuth_Config = array(); // Clean.
        
        $wgAuth_Config['WikiGroupName'] = 'Wiki';       // Name of your PHPBB group
                                                        // users need to be a member
                                                        // of to use the wiki. (i.e. wiki)
                                                        // This can also be set to an array 
                                                        // of group names to use more then 
                                                        // one. (ie. 
                                                        // $wgAuth_Config['WikiGroupName'][] = 'Wiki';
                                                        // $wgAuth_Config['WikiGroupName'][] = 'Wiki2';
                                                        // or
                                                        // $wgAuth_Config['WikiGroupName'] = array('Wiki', 'Wiki2');
                                                        // )
        
        
        $wgAuth_Config['UseWikiGroup'] = true;          // This tells the Plugin to require
                                                        // a user to be a member of the above
                                                        // phpBB group. (ie. wiki) Setting
                                                        // this to false will let any phpBB
                                                        // user edit the wiki.
        
        $wgAuth_Config['UseExtDatabase'] = true;       // This tells the plugin that the phpBB tables
                                                        // are in a different database then the wiki.
                                                        // The default settings is false.
        
        //$wgAuth_Config['MySQL_Host']        = 'localhost';      // phpBB MySQL Host Name.
        //$wgAuth_Config['MySQL_Username']    = '******************';       // phpBB MySQL Username.
        //$wgAuth_Config['MySQL_Password']    = '******************';       // phpBB MySQL Password.
        //$wgAuth_Config['MySQL_Database']    = '******************';       // phpBB MySQL Database Name.
        
        $wgAuth_Config['UserTB']         = 'phpbb_users';       // Name of your PHPBB user table. (i.e. phpbb_users)
        $wgAuth_Config['GroupsTB']       = 'phpbb_groups';      // Name of your PHPBB groups table. (i.e. phpbb_groups)
        $wgAuth_Config['User_GroupTB']   = 'phpbb_user_group';  // Name of your PHPBB user_group table. (i.e. phpbb_user_group)
        $wgAuth_Config['PathToPHPBB']    = '../forum/';         // Path from this file to your phpBB install.
        
        // Local
        $wgAuth_Config['LoginMessage']   = '<b>You need a phpBB account to login.</b><br /><a href="' . $wgAuth_Config['PathToPHPBB'] .
                                           'ucp.php?mode=register">Click here to create an account.</a>'; // Localize this message.
        $wgAuth_Config['NoWikiError']    = 'You are not a member of the required phpBB group.'; // Localize this message.
        
        $wgAuth = new Auth_phpBB($wgAuth_Config);     // Auth_phpBB Plugin.
`
Note: I masked those in * and phpBB prefix is phpbb_

**Comment by Digitalroot** [comment]
Change 
`//$wgAuth_Config['MySQL_Host']        = 'localhost';      // phpBB MySQL Host Name.
    //$wgAuth_Config['MySQL_Username']    = '******************';       // phpBB MySQL Username.
    //$wgAuth_Config['MySQL_Password']    = '******************';       // phpBB MySQL Password.
    //$wgAuth_Config['MySQL_Database']    = '******************';       // phpBB MySQL Database Name.`

to 

` $wgAuth_Config['MySQL_Host']        = 'localhost';      // phpBB MySQL Host Name.
    $wgAuth_Config['MySQL_Username']    = '******************';       // phpBB MySQL Username.
    $wgAuth_Config['MySQL_Password']    = '******************';       // phpBB MySQL Password.
    $wgAuth_Config['MySQL_Database']    = '******************';       // phpBB MySQL Database Name.`

**Comment by RotimiBolorunduro** [comment]
it's not working and i got this plain text page saying;

> Exception encountered, of type "Exception"

**Comment by Digitalroot** [comment]
That happens when those lines in my last comment are commented out.

**Comment by RotimiBolorunduro** [comment]
Okay, I sent you a mail i want to send my FTP details to you. lease check your mail @Digitalroot

**Comment by RotimiBolorunduro** [comment]
Is there anyone with a solution to this issue, Please i really need help. Thanks!

**Comment by RotimiBolorunduro** [comment]
Thank you Everyone for your Love and Guidance especially @Digitalroot, Thank you so much... The Integration is now working successfully. Also Thanks to @Kar2k @C4K3 @SteveGilvarry...
i guess this issue can now be closed, Good day.

**Comment by XnIcRaM** [comment]
Can you tell me solution for that problem? I have same problem.
